### ISSUE TITLE
rtcProps token

### ISSUE THREAD

**Issue by ismaelash** [AgoraIO-Community/ReactNative-UIKit#16]
Add token param on rtcProps no Readme

**Target device:** (Note: simulators are not supported for running the UIKit)
 - OS:
   - [X] IOS
   - [ ] Android
 - OS Version: [e.g. 22, 14.1]

**App Info** (Note: Expo CLI managed workflow is not supported by the UIKit)
 - Type:
   - [X] React Native CLI
   - [ ] Expo CLI - bare workflow
 - CLI Version: [e.g. 22]

**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
3. See error

**Screenshots**

**Comment by technophilic** [comment]
Thanks for the feedback, I'll document the `rtcProps` object

**Comment by EkaanshArora** [comment]
We've updated the documentation for the latest release with all the props documented here https://agoraio-community.github.io/ReactNative-UIKit/interfaces/propsinterface.html
