### ISSUE TITLE
Security Issues from Dependencies

### ISSUE THREAD

**Issue by maxxfrazer** [AgoraIO-Community/ReactNative-UIKit#23]
**Target device:** (Note: simulators are not supported for running the UIKit)
All

**App Info** (Note: Expo CLI managed workflow is not supported by the UIKit)
N/A

**Describe the issue**
There are security flags on this package. Specifically:
```
high      Lodash4.17.19->4.17.21
high      ajv6.11.0->v8.5.0
high      y18n4.0.0->y18n-v4.0.2
medium     hosted-git-infov2.8.5->v4.0.2
medium    mikaelbr/node-notifierv5.4.3->v9.0.1
medium    yargs-parserv13.1.1->20.2.7
```

**To Reproduce**
Some of the security issues are shown [here](https://github.com/AgoraIO-Community/ReactNative-UIKit/security/dependabot)
Others flagged by Black Duck Projects as seen below.

**Screenshots**
![8549EC33787A4CB7B06D6BAC65FAA8E7](https://user-images.githubusercontent.com/5754073/119657380-baad8980-be23-11eb-8fca-d50247147828.png)

**Comment by maxxfrazer** [comment]
@EkaanshArora could you take a look at this this week?

**Comment by EkaanshArora** [comment]
I've updated the UI Kit to v3.1.3 with updated dependencies that have the vulnerabilities fixed.

**Comment by maxxfrazer** [comment]
@EkaanshArora looks like Black Duck is still seeing the following vulnerabilities:
![image](https://user-images.githubusercontent.com/5754073/121695164-b4c1d480-cac2-11eb-8117-b81ec418d6af.png)

**Comment by maxxfrazer** [comment]
dependabot has opened a PR for one of them #25
