### ISSUE TITLE
Showing Blank screen

### ISSUE THREAD

**Issue by AahilShahzad** [AgoraIO-Community/ReactNative-UIKit#24]
**Target device:** (Note: simulators are not supported for running the UIKit)
 - Device: [ iPhone 8 plus]
 - OS:
   - [IOS] IOS
   - [ ] Android
 - OS Version: [14.5]

**App Info** (Note: Expo CLI managed workflow is not supported by the UIKit)
 - Type:
   - [Yes] React Native CLI
   - [ ] Expo CLI - bare workflow
 - CLI Version: [e.g. 22]

**Describe the issue**
showing blanks screen with error here is screenshot

**Screenshots**
<img width="580" alt="Screenshot 2021-05-27 at 5 20 25 PM" src="https://user-images.githubusercontent.com/13553516/119825072-04739e00-bf10-11eb-851e-c65de4cdca8f.png">

**Comment by AahilShahzad** [comment]
showing blank screen on both IOS and Android

**Comment by EkaanshArora** [comment]
Error 110 is for token expired/incorrect.
To run the project either use an App ID without a token (and pass the token as null). Or you can use a temporary token generated from the console (or using your own token server).

**Comment by AahilShahzad** [comment]
I'm running without token I  just create project in console agora and copy App ID from there and post in code.

**Comment by AahilShahzad** [comment]
here is code

<img width="1108" alt="Screenshot 2021-05-28 at 12 06 07 PM" src="https://user-images.githubusercontent.com/13553516/119944288-8239b700-bfad-11eb-974c-94b6e1790d7e.png">

**Comment by AahilShahzad** [comment]
here is console project
<img width="1389" alt="Screenshot 2021-05-28 at 12 10 20 PM" src="https://user-images.githubusercontent.com/13553516/119944489-c4fb8f00-bfad-11eb-9934-ec614aea2ee5.png">

**Comment by AahilShahzad** [comment]
its done
thanks for help
