### ISSUE TITLE
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module

### ISSUE THREAD

**Issue by wann2** [AgoraIO-Community/ReactNative-UIKit#28]
**Target device:** (Note: simulators are not supported for running the UIKit)
 - OS:
   - [X] IOS
   - [x] Android
 - OS Version: [e.g. 22, 14.1]

**App Info** (Note: Expo CLI managed workflow is not supported by the UIKit)
 - Type:
   - [X] React Native CLI
   - [ ] Expo CLI - bare workflow
 - CLI Version: [e.g. 22]

**Describe the issue**
 **ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.**

**To Reproduce**
1. Download the sample codes
2. execute [yarn]
3. I connected android devices on the PC
4. I updated my appId on ~/src/PropsContext.tsx
5. execute [npm start] on terminal#1
6. execute [npm run android] on terminal#2
7. I got BUILD SUCCESSFULL on terminal#2
8. But when the app played on the android device, I always got the below error.

**Screenshots**
<img width="797" alt="스크린샷 2021-06-21 오전 11 52 09" src="https://user-images.githubusercontent.com/8732515/122701032-57c6db00-d287-11eb-91f8-f78ec617d2d0.png">

**Comment by EkaanshArora** [comment]
This repo is the source code for the UI Kit, it isn't intended to be built and ran like your comment.
You can find a demo project utilising the UI Kit [here](https://github.com/AgoraIO-Community/ReactNative-UIKit-example). You can clone and run this instead. I'll update the readme to reference this for the future.

There's also a [setup guide](https://github.com/AgoraIO-Community/ReactNative-UIKit/wiki/Setup) in the wiki.

**Comment by EkaanshArora** [comment]
To avoid confusion in the future, we'll remove the react-native files from this repo in the next release.
