### ISSUE TITLE
Camera and micro don't work

### ISSUE THREAD

**Issue by nghia703** [AgoraIO-Community/ReactNative-UIKit#29]
Hi @EkaanshArora 

I have built and can ran the project. The permission for camera, micro are granted but an error 109 occurred in the console
The camera and micro don't work, the screen always black as screenshot below

![image](https://user-images.githubusercontent.com/16395307/123079420-221c2080-d446-11eb-9d34-802b6bf82f86.png)

Can you help ?
Many thanks

**Comment by EkaanshArora** [comment]
The simulator doesn't support using the camera, please use a physical device to test.

**Comment by nghia703** [comment]
Yes, the issue was in physical device, I just screenshot the simulator to understand easier.

**Comment by EkaanshArora** [comment]
Did you add permission text for camera and microphone is Xcode?

**Comment by maxxfrazer** [comment]
Error 109 means the token expired, please use a valid token generated from a token server or a temporary token generated within 24 hours

**Comment by nghia703** [comment]
Thanks @maxxfrazer.

@EkaanshArora: I think it would be perfect the document should be updated by adding how to config the token in App.js

**Comment by EkaanshArora** [comment]
Sure thing, I'll update the readme/wiki. Thanks for the feedback.
