### ISSUE TITLE
Local control icons not loading on iOS

### ISSUE THREAD

**Issue by umairlive490** [AgoraIO-Community/ReactNative-UIKit#32]
[](url)**Target device:** (Note: simulators are not supported for running the UIKit)
 - Device: [e.g. iPhone7 plus]
 - OS:
   - [X] IOS
 - OS Version: [14.3]

**App Info** (Note: Expo CLI managed workflow is not supported by the UIKit)
 - Type:
   - [X] React Native CLI
 - CLI Version: [2.0.1]

**Describe the issue**
Local control icons sometimes take up to 1 minute to show up

**To Reproduce**
Steps to reproduce the behaviour:
1. Place call
2. Observe Local control icons not loading on iOS

**Screenshots**
![image-2021-08-04-17-34-57-930](https://user-images.githubusercontent.com/38652281/128678338-d45d88dd-c719-4bde-8677-1653b769a4af.png)

**Comment by maxxfrazer** [comment]
@EkaanshArora I don't remember seeing this when I ran it on iOS, have you seen this ever?

**Comment by EkaanshArora** [comment]
I haven't seen this before, @umairlive490 are you using custom images for the icons?

**Comment by umairlive490** [comment]
@EkaanshArora No i am not using my own icons.I just used UIKit provided icons and here is my styleProps
 const videoStyleProp = {
    videoMode: {
      max: VideoRenderMode.Hidden,
      min: VideoRenderMode.Hidden,
    },
    localBtnContainer: {
      marginVertical: 20,
    },
    remoteBtnContainer: {
      display: 'none'
    },
    minViewContainer: {
      padding: 5,
      width: 200
    },
    minViewStyles: {
      height: 200,
      width: 200,
    }
  };

**Comment by umairlive490** [comment]
@EkaanshArora It doesn't happen every time but some time this issue is occurring.
One more thing i wanted to make minView as square but on iOS it is not becoming square for equal height and width 200*200

**Comment by EkaanshArora** [comment]
It's hard to help without being able to reproduce the issue. Can you confirm if you see this problem in the production build?

I used your styling (`minViewStyles: {height: 200, width: 200}`) in the above screenshot, it's running on an iPhone and appears to be square. I'm not sure I follow.
