### ISSUE TITLE
Can't find variable mode, role

### ISSUE THREAD

**Issue by SunaPanaReloaded** [AgoraIO-Community/ReactNative-UIKit#33]
Newbie here.

Below is my code. I want to create a live stream using the plugin but when I  use `mode: mode.LiveBroadcasting` it says variable mode not found. I read your wiki and used the rtcProps.

`import React, { useState } from 'react';
import AgoraUIKit from 'agora-rn-uikit';

const App = () => {
  const [videoCall, setVideoCall] = useState(true);
  const rtcProps = {
    appId: 'APP_ID,
    channel: 'test',
    mode: mode.LiveBroadcasting,
    role: role.Audience,
    uid: 1,
  };
  const callbacks = {
    EndCall: () => setVideoCall(false),
  };
  return videoCall ? (
    <AgoraUIKit rtcProps={rtcProps} callbacks={callbacks} />
  ) : (
    <></>
  );
};

export default App;`

**Comment by EkaanshArora** [comment]
They are enums that you can import from the library like so:
`import AgoraUIKit, {mode, role} from 'agora-rn-uikit';`
