### ISSUE TITLE
Adding Custom Buttons // Remove/Change Default LocalControls

### ISSUE THREAD

**Issue by Asher978** [AgoraIO-Community/ReactNative-UIKit#35]
Hello,

Is there a way to add custom buttons?
Is there a way to change/remove the default LocalControl?

How can we utilize the `<RtcConfigure>` component and add custom components?

**Comment by EkaanshArora** [comment]
Hi @Asher978!
You can pass in custom base64 png for button icons in the styleProps using the [customIcon property](https://agoraio-community.github.io/ReactNative-UIKit/interfaces/stylepropinterface.html#customicon).
If you want to make your own button to perform some function you can use the btnTemplate component to create it and then [recompose the app](https://github.com/AgoraIO-Community/ReactNative-UIKit/wiki/Examples#recomposing-the-app). 

To remove the localControls you can just pass in `display: 'none'` in the styleProp to hide it.

Take a look at the [recomposing example](https://github.com/AgoraIO-Community/ReactNative-UIKit/wiki/Examples#recomposing-the-app) in the wiki to see how to add custom components.
