### ISSUE TITLE
ReactNative-UIKit with Banuba integration

### ISSUE THREAD

**Issue by gtsopour** [AgoraIO-Community/ReactNative-UIKit#36]
Hello guys,
do you have any suggestion or any ideas about a possible integration of ReactNative-UIKit with Banuba?

Best
George

**Comment by EkaanshArora** [comment]
Hi, you'll have to use the underlying native iOS and Android SDKs to add [Banuba integration](https://www.agora.io/en/agora-extensions-marketplace/banuba/), we're looking into making this easier in the future, but it's not in our immediate roadmap.

**Comment by gtsopour** [comment]
@EkaanshArora thanks a lot for your feedback. So practically you mean that I have to integrate natively first the Agora SDK with the Banuba SDK as it is described here https://www.banuba.com/faq/how-to-integrate-banuba-sdk-with-agora-sdk for both iOS and Android and then kind of adapt/rewrite the React Native Agora https://github.com/AgoraIO-Community/react-native-agora plugin over my native integration?

Thanks in advance.
