### ISSUE TITLE
Inproper setState while executing Endcall Call Back

### ISSUE THREAD

**Issue by Asher978** [AgoraIO-Community/ReactNative-UIKit#40]
I am getting the below error while creating a minimal example shown in your example.

`
Cannot update a component <Call /> while rendering a different component <RtcConfigure />. To locate the bad setState() call inside `RtcConfigure`, follow the stack trace ...
`

``` js
const Call = ({ CK }) => {
  const [videoCall, setVideoCall] = useState(true);

  const callbacks = {
    EndCall: () => {
      //   CK.endCall();
      setVideoCall(false);
    },
  };

  const rtcProps = {
    appId: "###########################",
    channel: "test",
  };

  const styleProps = {
    UIKitContainer: { height: "100%" },
    // localBtnContainer: { display: "none" },
    videoMode: {
      max: VideoRenderMode.Hidden,
      min: VideoRenderMode.Hidden,
    },
  };

  return (
    <SafeAreaView
      style={{
        flex: 1,
      }}
    >
      <AgoraUIKit
        rtcProps={rtcProps}
        styleProps={styleProps}
        mode={1}
        callbacks={callbacks}
      />
    </SafeAreaView>
  );
};
`

**Comment by UmerQadri** [comment]
@Asher978 I am not having this issue but I noticed one thing. `mode` should be passed in rtcProps, not directly as `AgoraUIKit` prop

**Comment by Asher978** [comment]
@UmerQadri if you try to navigate to a different screen right after the call is ended, you will see the above error.

**Comment by UmerQadri** [comment]
@Asher978 it doesn't happen to me. Try to remove the set state from the `EndCall` callback, I think this is causing the problem for some reason

**Comment by EkaanshArora** [comment]
I'll take a look into this, but the warning should be safe to ignore. Is it causing any issues in your app?

**Comment by pankajgoyal28** [comment]
Is it resolved, i am facing similar issue
