### ISSUE TITLE
I need share screen in my app

### ISSUE THREAD

**Issue by ronny141** [AgoraIO-Community/ReactNative-UIKit#48]
**Target device:** (Note: simulators are not supported for running the UIKit)
 - OS:
   - [X] IOS
   - [X] Android
 - OS Version: [e.g. 22, 14.1]

**App Info**
 - Type:
   - [X] React Native CLI
   - [ ] Expo CLI (using custom development clients)
 - CLI Version: [e.g. 22]

**Describe the issue**
I need share screen in my app
someone has been able to share screen using the Agora UIKit

**Comment by EkaanshArora** [comment]
Screen sharing isn't part of the Agora React Native SDK yet. Once it's part of the official SDK, we'll add it to the UIKit.
