### ISSUE TITLE
No podspec file was found.

### ISSUE THREAD

**Issue by iRayan7** [AgoraIO-Community/ReactNative-UIKit#5]
Hey, thanks for the great work!

Whenever I `pod install` inside `ios/` I get this warning:
```
[!] use_native_modules! skipped the react-native dependency 'agora-rn-uikit'. No podspec file was found.
    - Check to see if there is an updated version that contains the necessary podspec file
    - Contact the library maintainers or send them a PR to add a podspec. The react-native-webview podspec is a good example of a package.json driven podspec. See
    https://github.com/react-native-community/react-native-webview/blob/master/react-native-webview.podspec
    - If necessary, you can disable autolinking for the dependency and link it manually. See
    https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-disable-autolinking-for-unsupported-library
```

<details>
<summary>react-native info</summary>

System:
  Binaries:
    Node: 10.15.1 - /usr/local/bin/node
    Yarn: 1.21.1 - ~/n/bin/yarn
    npm: 6.4.1 - ~/n/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.7.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.2, 28.0.3, 29.0.0, 29.0.0
      System Images: android-26 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Android TV Intel x86 Atom, android-28 | China version of Wear OS Intel x86 Atom, android-28 | Wear OS Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
      Android NDK: 19.2.5345600
  IDEs:
    Android Studio: 3.4 AI-183.5429.30.34.5452501
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_60 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

</details>

Thanks.

**Comment by EkaanshArora** [comment]
Hey, can you check if you can use the library still if you just ignore this error?

**Comment by davisuga** [comment]
The library just can't be actually used on iOS.

**Comment by technophilic** [comment]
This library is a pure JS library. It has no native modules and it won't require any podspec file. We'll be removing the android and ios folders in the next update. @davisuga The issue w IOS might probably be around permissions not present not the podspec.
