### ISSUE TITLE
Getting Black screen with icons

### ISSUE THREAD

**Issue by syedfahadhussain-rn** [AgoraIO-Community/ReactNative-UIKit#52]
**Target device:** (Note: simulators are not supported for running the UIKit)
 - Device: [Honor 9n and emulator]
 - OS:
   - [ ] Android
 - OS Version: [Android 10]

**App Info**
 - Type:
   - [ ] React Native CLI
 - CLI Version: [0.66.4]

**Describe the issue**
 LOG  Running "AgoraSample" with {"rootTag":51}
 LOG  Attempted join:  TestCalling
 LOG  You can use the cameras & mic
 LOG  {"_listeners": Map {}}
 LOG  Running "AgoraSample" with {"rootTag":61}
 LOG  Attempted join:  TestCalling
 LOG  You can use the cameras & mic
 LOG  {"_listeners": Map {}}

![Screenshot_1643697464](https://user-images.githubusercontent.com/91606927/151923782-8f08fc8c-124f-4ee4-b04d-4bea86be50af.png)

**Comment by syedfahadhussain-rn** [comment]
I have passing tokens and without token still getting the blank screen

**Comment by EkaanshArora** [comment]
Can you share your code?

**Comment by syedfahadhussain-rn** [comment]
sure,
import React, {useState} from 'react';
import AgoraUIKit from 'agora-rn-uikit';
import { Text } from 'react-native';

const App = () => {
  const [videoCall, setVideoCall] = useState(true);
  const rtcProps = {
    appId: 'c6b259af0e404646ae6565f63a7c4263',
    channel: 'TestCalling',
    token:'006bc44e550dc5a4b7bb6877ffaa19b7b95IABpAhEywnuKqrGzv3++mk6UKHQ3N9o1WHfKn0dIqWPZt5WTzYEAAAAAEAD1z9KP+SP6YQEAAQBMI/ph',
  };
  const callbacks = {
    EndCall: () => setVideoCall(false),
  };
  return videoCall ? (
    <AgoraUIKit rtcProps={rtcProps} callbacks={callbacks} />
  ) : (
    <Text onPress={()=>setVideoCall(true)}>Start Call</Text>
  );
};

export default App;

**Comment by EkaanshArora** [comment]
Did you forget to render the UIKit?
```jsx
...
return videoCall ? (
<AgoraUIKit rtcProps={rtcProps} callbacks={callbacks} />
) : (
...
```

**Comment by syedfahadhussain-rn** [comment]
Yes I have rendered UIkit but it is not showing properly in comment @EkaanshArora .

**Comment by EkaanshArora** [comment]
Do you get any errors in the console? It's hard to think of a possible issue with the limited information.

**Comment by syedfahadhussain-rn** [comment]
@EkaanshArora ,

**Comment by EkaanshArora** [comment]
Can you reproduce the issue with [this repo](https://github.com/AgoraIO-Community/ReactNative-UIKit-example) on your device? Can you also try this [sample app](https://github.com/AgoraIO-Community/agora-rn-quickstart)?

**Comment by syedfahadhussain-rn** [comment]
I have tried to reproduce using the above repo but getting,

**Comment by EkaanshArora** [comment]
I just did a fresh clone of the project, added my AppID and ran it on the Android Emulator. Works fine for me.

**Comment by syedfahadhussain-rn** [comment]
Can you please tell me which example you have ran..? @EkaanshArora

**Comment by EkaanshArora** [comment]
This one: https://github.com/AgoraIO-Community/ReactNative-UIKit-example

**Comment by syedfahadhussain-rn** [comment]
@EkaanshArora

**Comment by syedfahadhussain-rn** [comment]
@EkaanshArora 

I have also tried to clone the project and facing error
  callback not found {"children": [<Context.Consumer>[Function anonymous]</Context.Consumer>, <ForwardRef(ScrollView) horizontal={true} showsHorizontalScrollIndicator={false} style={[Object]}><Context.Consumer … /></ForwardRef(ScrollView)>, <Controls />]}

**Comment by syedfahadhussain-rn** [comment]
I have checked that agora won't supporting in android version more than 10 @EkaanshArora
