### ISSUE TITLE
Displaying multiple SurfaceView of same UID

### ISSUE THREAD

**Issue by parallelmedical** [AgoraIO-Community/ReactNative-UIKit#53]
is is possible to render multiple surface views of the same UID? For example if using a gridview can you popup a modal with the same surface views? at the moment only the newest rendered surface-views actually show the video, the others go grey

**Comment by EkaanshArora** [comment]
This isn't possible with the current SDK implementation. You can open a feature request at [react-native-agora](https://github.com/AgoraIO-Community/react-native-agora).
