### ISSUE TITLE
callbacks for fullscreen, mute audio/video not getting executed.

### ISSUE THREAD

**Issue by Pranav-19** [AgoraIO-Community/ReactNative-UIKit#6]
Callback functions which I am passing for fullscreen, mute audio/video buttons are not getting executed. 
This is the callbacks object I am passing -
{
	onEndCall: () => { this.setState({ videoCall: false }) }
	onFullScreen: ()=>{ this.onFullScreen()}
}
The callback for endcall is working fine but FullScreen is not getting executed. Same is the issue for mute audio/video buttons.

**Comment by technophilic** [comment]
Hey, can you check if you are facing this in the latest version?
It has been updated to v3 of the Agora React Native SDK

**Comment by technophilic** [comment]
Closed due to inactivity
