### ISSUE TITLE
Agora Would Let App Build

### ISSUE THREAD

**Issue by abisalde** [AgoraIO-Community/ReactNative-UIKit#62]
**Target device:** (Note: simulators are not supported for running the UIKit)
 - OS:
   - [] IOS
   - [X ] Android
 - OS Version: [e.g. 22, 14.1]

**App Info**
 - Type:
   - [X] React Native CLI
   - [ ] Expo CLI (using custom development clients)
 - CLI Version: [e.g. 22]

**Describe the issue**
```
[stderr] * What went wrong:
[stderr] Could not determine the dependencies of task ':app:lintVitalRelease'.
[stderr] > Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
[stderr]    > Could not find native-full-sdk-3.5.2.jar (com.github.agorabuilder:native-full-sdk:3.5.2).
[stderr]      Searched in the following locations:
[stderr]          https://www.jitpack.io/com/github/agorabuilder/native-full-sdk/3.5.2/native-full-sdk-3.5.2.jar
```
**To Reproduce**
1. Trying to run build the app with `npx react-native run-android` and bundle the app with ./gradlew release

**Screenshots**
![LONG](https://user-images.githubusercontent.com/38655623/165169655-c75a9135-df17-4d5f-83aa-6af342125070.png)

**Comment by abisalde** [comment]
Hi @EkaanshArora,

I tried visiting this URL below, but was showing Not found, and I think it may have something to do with the URL

https://www.jitpack.io/com/github/agorabuilder/native-full-sdk/3.5.2/native-full-sdk-3.5.2.jar

**Comment by EkaanshArora** [comment]
You're right, can you update your version of the sdk? `npm i react-native-agora`

**Comment by abisalde** [comment]
OK, Thanks, Let me do just that
