### ISSUE TITLE
RtcEvents

### ISSUE THREAD

**Issue by honey10597** [AgoraIO-Community/ReactNative-UIKit#64]
Hello everyone,

can anyone help me to implement the RtcEvents listner. 
For eg :- When particular users join or end call, some warning and error issues, etc.

How can I implement that? There is no documation for this .

**Comment by EkaanshArora** [comment]
If you're using the v4 of the uikit, you can use the `rtcCallbacks` prop to add events example:
```jsx
       <AgoraUIKit
          connectionData={{
            appId: appid,
            channel: 'test',
          }}
          rtcCallbacks={{
            UserJoined: e => console.log(e)
          }}
        />
```
On v3 of the uikit, this prop is called `callbacks`

**Comment by honey10597** [comment]
> If you're using the v4 of the uikit, you can use the `rtcCallbacks` prop to add events example:
> 
> ```js
>        <AgoraUIKit
>           connectionData={{
>             appId: appid,
>             channel: 'test',
>           }}
>           rtcCallbacks={{
>             UserJoined: e => console.log(e)
>           }}
>         />
> ```
> 
> On v3 of the uikit, this prop is called `callbacks`

Basically I am Implementing Live Streaming by using agora-rn-uikit. But unfortunality, I am unable to see the no. of audience or users who are currently watching my live session.

**Comment by EkaanshArora** [comment]
Update to the v4.0.0 of the UIKit and use the RTM callbacks to get audience count like so:
```jsx
      <AgoraUIKit
          connectionData={{
            appId: appid,
            channel: 'test',
          }}
          rtmCallbacks={{
            ChannelMemberJoined: (e) => {
              //increment count
            },
            ChannelMemberLeft: (e) => {
              //decrement count
            },
          }}
        />
```
RTM is only added in v4, so you'll have to update your code.

**Comment by honey10597** [comment]
I am getting an error.

**Comment by honey10597** [comment]
> Update to the v4.0.0 of the UIKit and use the RTM callbacks to get audience count like so:
> 
> ```js
>       <AgoraUIKit
>           connectionData={{
>             appId: appid,
>             channel: 'test',
>           }}
>           rtmCallbacks={{
>             ChannelMemberJoined: (e) => {
>               //increment count
>             },
>             ChannelMemberLeft: (e) => {
>               //decrement count
>             },
>           }}
>         />
> ```
> 
> RTM is only added in v4, so you'll have to update your code.

Getting an error  in **RtmConfigure.tsx**-- error file is attached with .

And not getting any callback in **rtmCallbacks**
My code is :-

![Screenshot 2022-05-19 at 2 58 03 PM](https://user-images.githubusercontent.com/42267565/169261261-2f547642-6c3b-4372-a0f6-862d1f8e2df9.png)
.

**Comment by EkaanshArora** [comment]
The [connectionData](https://agoraio-community.github.io/ReactNative-UIKit/interfaces/ConnectionData.html) prop expects `rtcToken`, `rtcUid`, `rtmToken`, `rtmUid`.  
Can you double check these value?

**Comment by honey10597** [comment]
> The [connectionData](https://agoraio-community.github.io/ReactNative-UIKit/interfaces/ConnectionData.html) prop expects `rtcToken`, `rtcUid`, `rtmToken`, `rtmUid`. Can you double check these value?

yes. I have checked everything.I did everything according to your way also.
My RTM working fine with Native IOS Sdk , But gives Login failed error in only agora-rn-uikit. Problem is only with RTM. Except this, all things are working fine.

can you please recheck again ?

**Comment by EkaanshArora** [comment]
Are you using two different `rtmUid`s and `rtcToken`s for the two clients? I'm unable to reproduce the issue. Used a new project with the proper tokens and it works across web and react-native. 
![image](https://user-images.githubusercontent.com/10047883/169524447-2b461988-6d57-4fef-be07-eaaa42a0d4a8.png)

**Comment by honey10597** [comment]
Hello,
one to one and one to many video call is working fine.When I set the settings for live streaming rtm gives an error related to LOGIN FAILURE.

you can check at your side with my agora credentials.
APP ID : ac48dd62bef64f23b8bc13e6e7f08e09
CERTIFICATE : 2d8691e4128e4731a7e7776a45ab3d04
