### ISSUE TITLE
UIkit enabling dual stream undefined

### ISSUE THREAD

**Issue by lexiconcpl** [AgoraIO-Community/ReactNative-UIKit#66]
" UIkit enabling dual stream undefined " , I am getting this while running  the same code explained in this link -https://github.com/AgoraIO-Community/ReactNative-UIKit#readme. Can any one help me on understanding what else I am missing

**Comment by EkaanshArora** [comment]
Dual stream is an optional feature which is disabled by default, the log is safe to ignore. Are you facing any issues?
